### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by gintaresaali** [FUKA-INNOVATIONS/Safeye#30]
Send alert to TCs.
Override volume settings.
Permissions...

**Comment by FUKA-INNOVATIONS** [comment]
Device media player volume can be overridden on app startup
Test repo: https://github.com/FUKA-INNOVATIONS/iOS-VolumeDictator

There are 2 types of volumes in iOS device, since we are going to play alert sound as an inApp, the choice is to adjust mediaPlayer volume level. This action can be taken at any stage and any screen.

For trusted contacts, we have to consider -> when to adjust contact's volume level, maybe 1 option is to connect this to the database Event document:

1. Trusted contact subscribes to event status changes
2. Event status changes to Panic
3. Trusted contact media player volume is set to MAX
4. Play sound alert

**Comment by FUKA-INNOVATIONS** [comment]
Event flow diagram
https://drive.google.com/file/d/1eoeaxc7SzLdCQ6y0gqssIt8UC51r289h/view?usp=sharing
