### ISSUE TITLE
Create and manage event

### ISSUE THREAD

**Issue by gintaresaali** [FUKA-INNOVATIONS/Safeye#40]
After #37 

Tracked person flow:
- [x] Create new event : requires min 1 existing TC
- [x] View Event details
- [x] Change event status ( start, pause, panic )
- [x] Delete
 - - - - -
- [x] Create models
- [x] Create viewModels
- [x] Create services
- [x] Customize event view for trusted contact

-----------
Service : App state is always updated with latest state on these operations
- [x] Create new event
- [x] Get event details
- [x] Update event details
- [x] Get Events of authenticated/current user
- [x] Change event status
- [x] Delete event
- [x] Subscribe / listen to event changes

**Comment by FUKA-INNOVATIONS** [comment]
Event flow ( initial )
https://drive.google.com/drive/folders/1dl30EsKOxe3nJjQ2wKbOziz1eL8q-sIJ

**Comment by FUKA-INNOVATIONS** [comment]
Creating event and adding trusted contact from users own established connections (accepted requests)  done, I wonder how far should I yet take this at this stage.      At the moment I have limited the user to have ONLY ONE event since we yet dont  have  a list view to list users various events but enabling this fueature has been taken into considersation and is easy to do
User can ofcourse select and deselect trusted contact while creating the event 
Plus, user must select at least 1 contact to be able to create an event, this configuration can also be changed easily
